src/Entity/Announcement.php
<?php

namespace App\Entity;

use App\Repository\AnnouncementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnnouncementRepository::class)
 */
class Announcement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text", length=65535)
     */
    private $Description;

    /**
     * @ORM\Column(type="date")
     */
    private $DatePublish;

    /**
     * @ORM\Column(type="boolean")
     */
    private $IsActive;

    /**
     * @ORM\Column(type="float")
     */
    private $Price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    public function getId(): ?int
    {
        return $this->id;
    }

    /////////////////////////Link between Annnouncement & User////////////////////

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="Announcements")
     */
    private $User;

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    ////////////////////////////////////////////


    ////////////////////////Link between Annnouncement & Category////////////////////

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="Announcements")
     */
    private $Category;

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    /////////////////////////////////////////////////////////////////////

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDatePublish(): ?\DateTimeInterface
    {
        return $this->DatePublish;
    }

    public function setDatePublish(\DateTimeInterface $DatePublish): self
    {
        $this->DatePublish = $DatePublish;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->IsActive;
    }

    public function setIsActive(bool $IsActive): self
    {
        $this->IsActive = $IsActive;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
    
}

templates/account.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<div class="container mt-5 mb-80">
		<div class="row">
			<div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
				<div class="well profile">
					<div class="col-sm-12">
						<div class="col-xs-12 col-sm-8">
							<h2>{{ user.getFirstName }} {{ user.getLastName }}</h2>
							<p><strong>Téléphone: </strong> {{user.getPhone}} </p>
							<p><strong>Email: </strong> {{ user.getUsername }} </p>
							<p><strong>Adresse: </strong> {{ user.getAddress }} </p>
							<p><strong>Code Postale : </strong> {{ user.getCodePoste }} </p>
							<p><strong>Ville: </strong> {{user.getCity}} </p>
						</div>             
					</div>            
				</div>                 
			</div>


			<div class="col-md-2 ml-18 text-center">
 			<!--<div class="profile-userpic">
				<img src="https://i.stack.imgur.com/l60Hf.png" class="img-responsive" alt="">
			</div>-->
			<p><strong>Votre crédit</strong></p>
			<h2><strong> 20 € </strong></h2>                    
			<button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span>Créditer Compte</button>

			<div class="mb-3 mt-20">
				<a class="btn btn-primary btn-block" href="{{ path('createannouncementview') }}">Créer Annonce</a>
			</div>

			<div class="mb-3 mt-20">
				<a class="btn btn-danger btn-block" href="{{ path('app_logout') }}">Déconnexion</a>
			</div>

		</div>
	</div>
</div>


<div class="container">

	<div class="accordion" id="accordionExample">
		<div class="card">
			<div class="card-header" id="headingOne">
				<h2 class="mb-0">
					<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
						Liste des mes annonces
					</button>
				</h2>
			</div>

			<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
				<div class="card-body">
					<!--Announcements-->
					<div class="row">
						{% for announcement in announcements %}
							<div class="col-lg-4 col-md-6 mb-4 ml-5">
								<div class="card h-100">
									<a href="#"><img class="card-img-top" src="{{announcement.Image}}" alt=""></a>
									<div class="card-body">
										<h4 class="card-title">
											<a href="{{ path('announcement', {'id': announcement.id}) }}">{{announcement.Title}}</a>
										</h4>
										<h5>{{announcement.Price}}€</h5>
										<p class="card-text">{{announcement.Description|length > 200 ? announcement.Description|slice(0, 200) ~ '...' : announcement.Description}}</p>
									</div>
									<div class="card-footer">
										<a href="{{ path('deleteAnnouncement', {'id': announcement.id}) }}">Supprimer
											<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
												<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
												<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
											</svg>
										</a>
										<small class="text-muted"></small>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
		<div class="card">
			<div class="card-header" id="headingTwo">
				<h2 class="mb-0">
					<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
						Les services que j'ai payé
					</button>
				</h2>
			</div>
			<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
				<div class="card-body">
					<!--I have paie-->
					
				</div>
			</div>
		</div>
	</div>

</div>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
  		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  		<meta name="description" content="">
  		<meta name="author" content="">
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <title>{% block title %}vendstonproduit{% endblock %}</title>

        {% block stylesheets %}

        	<link rel="stylesheet" href="/vendstonproduit/templates/style/css/bootstrap-grid.css">
        	<link rel="stylesheet" href="/vendstonproduit/templates/style/css/bootstrap-reboot.css">
        	<link rel="stylesheet" href="/vendstonproduit/templates/style/css/bootstrap.css">
        	<link rel="stylesheet" href="/vendstonproduit/templates/style/css/shop-homepage.css">
        	<link rel="stylesheet" href="/vendstonproduit/templates/style/css/bootstrap-extras-margins-padding.css">
        	<link rel="stylesheet" href="/vendstonproduit/templates/style/css/style.css">
        	
        {% endblock %}
    </head>
    <body>
    	<!-- Navigation -->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
			<div class="container">
			  <a class="navbar-brand" href="{{ path('index') }}">One minute</a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarResponsive">
			    <ul class="navbar-nav ml-auto">
			      <li class="nav-item active">
			        <a class="nav-link" href="{{ path('index') }}">Accueil
			          <span class="sr-only">(current)</span>
			        </a>
			      </li>
			      <li class="nav-item">
			      	{% if app.user %}
			      		<a class="nav-link" href="{{ path('account') }}">Mon Compte</a>
			      	{% else %}
			      		<a class="nav-link" href="{{ path('login') }}">Connexion</a>	
			      	{% endif %}
			       
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{{ path('declaration') }}">Déclarer Revenues</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="#">Nos services</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{{ path('contact') }}">Contact</a>
			      </li>
			    </ul>
			  </div>
			</div>
		</nav>
		
        {% block body %}


        {% endblock %}

		<footer class="footer py-5 bg-dark">
			<div class="container">
			  <p class="m-0 text-center text-white">Copyright &copy; One Minute 2020</p>
			</div>
		<!-- /.container -->
		</footer>

        {% block javascripts %}
        	<script type="text/javascript" src="/vendstonproduit/templates/style/jquery/jquery.min.js"></script>
        	<script type="text/javascript" src="/vendstonproduit/templates/style/js/bootstrap.js"></script>
        	<script type="text/javascript" src="/vendstonproduit/templates/style/js/bootstrap.bundle.min.js"></script>
        {% endblock %}
    </body>
</html>

templates/cart.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<!--Section: Block Content-->
	<section>

	  <!--Grid row-->
	  <div class="row">

	    <!--Grid column-->
	    <div class="col-lg-8">

	      <!-- Card -->
	      <div class="mb-3">
	        <div class="pt-4 wish-list">

	          <h5 class="mb-4">Cart (<span>2</span> items)</h5>

	          <div class="row mb-4">
	            <div class="col-md-5 col-lg-3 col-xl-3">
	              <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
	                <img class="img-fluid w-100"
	                  src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12a.jpg" alt="Sample">
	                <a href="#!">
	                  <div class="mask">
	                    <img class="img-fluid w-100"
	                      src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg">
	                    <div class="mask rgba-black-slight"></div>
	                  </div>
	                </a>
	              </div>
	            </div>
	            <div class="col-md-7 col-lg-9 col-xl-9">
	              <div>
	                <div class="d-flex justify-content-between">
	                  <div>
	                    <h5>Blue denim shirt</h5>
	                    <p class="mb-3 text-muted text-uppercase small">Shirt - blue</p>
	                    <p class="mb-2 text-muted text-uppercase small">Color: blue</p>
	                    <p class="mb-3 text-muted text-uppercase small">Size: M</p>
	                  </div>
	                  <div>
	                    <div class="def-number-input number-input safari_only mb-0 w-100">
	                      <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()"
	                        class="minus decrease"></button>
	                      <input class="quantity" min="0" name="quantity" value="1" type="number">
	                      <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()"
	                        class="plus increase"></button>
	                    </div>
	                    <small id="passwordHelpBlock" class="form-text text-muted text-center">
	                      (Note, 1 piece)
	                    </small>
	                  </div>
	                </div>
	                <div class="d-flex justify-content-between align-items-center">
	                  <div>
	                    <a href="#!" type="button" class="card-link-secondary small text-uppercase mr-3"><i
	                        class="fas fa-trash-alt mr-1"></i> Remove item </a>
	                    <a href="#!" type="button" class="card-link-secondary small text-uppercase"><i
	                        class="fas fa-heart mr-1"></i> Move to wish list </a>
	                  </div>
	                  <p class="mb-0"><span><strong id="summary">$17.99</strong></span></p class="mb-0">
	                </div>
	              </div>
	            </div>
	          </div>
	          <hr class="mb-4">
	          <div class="row mb-4">
	            <div class="col-md-5 col-lg-3 col-xl-3">
	              <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
	                <img class="img-fluid w-100"
	                  src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13a.jpg" alt="Sample">
	                <a href="#!">
	                  <div class="mask">
	                    <img class="img-fluid w-100"
	                      src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13.jpg">
	                    <div class="mask rgba-black-slight"></div>
	                  </div>
	                </a>
	              </div>
	            </div>
	            <div class="col-md-7 col-lg-9 col-xl-9">
	              <div>
	                <div class="d-flex justify-content-between">
	                  <div>
	                    <h5>Red hoodie</h5>
	                    <p class="mb-3 text-muted text-uppercase small">Shirt - red</p>
	                    <p class="mb-2 text-muted text-uppercase small">Color: red</p>
	                    <p class="mb-3 text-muted text-uppercase small">Size: M</p>
	                  </div>
	                  <div>
	                    <div class="def-number-input number-input safari_only mb-0 w-100">
	                      <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()"
	                        class="minus"></button>
	                      <input class="quantity" min="0" name="quantity" value="1" type="number">
	                      <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()"
	                        class="plus"></button>
	                    </div>
	                  </div>
	                </div>
	                <div class="d-flex justify-content-between align-items-center">
	                  <div>
	                    <a href="#!" type="button" class="card-link-secondary small text-uppercase mr-3"><i
	                        class="fas fa-trash-alt mr-1"></i> Remove item </a>
	                    <a href="#!" type="button" class="card-link-secondary small text-uppercase"><i
	                        class="fas fa-heart mr-1"></i> Move to wish list </a>
	                  </div>
	                  <p class="mb-0"><span><strong>$35.99</strong></span></p class="mb-0">
	                </div>
	              </div>
	            </div>
	          </div>
	          <p class="text-primary mb-0"><i class="fas fa-info-circle mr-1"></i> Do not delay the purchase, adding
	            items to your cart does not mean booking them.</p>

	        </div>
	      </div>
	      <!-- Card -->

	      <!-- Card -->
	      <div class="mb-3">
	        <div class="pt-4">

	          <h5 class="mb-4">Expected shipping delivery</h5>

	          <p class="mb-0"> Thu., 12.03. - Mon., 16.03.</p>
	        </div>
	      </div>
	      <!-- Card -->

	      <!-- Card -->
	      <div class="mb-3">
	        <div class="pt-4">

	          <h5 class="mb-4">We accept</h5>

	          <img class="mr-2" width="45px"
	            src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
	            alt="Visa">
	          <img class="mr-2" width="45px"
	            src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
	            alt="American Express">
	          <img class="mr-2" width="45px"
	            src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
	            alt="Mastercard">
	          <img class="mr-2" width="45px"
	            src="https://mdbootstrap.com/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png"
	            alt="PayPal acceptance mark">
	        </div>
	      </div>
	      <!-- Card -->

	    </div>
	    <!--Grid column-->

	    <!--Grid column-->
	    <div class="col-lg-4">

	      <!-- Card -->
	      <div class="mb-3">
	        <div class="pt-4">

	          <h5 class="mb-3">The total amount of</h5>

	          <ul class="list-group list-group-flush">
	            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
	              Temporary amount
	              <span>$25.98</span>
	            </li>
	            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
	              Shipping
	              <span>Gratis</span>
	            </li>
	            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
	              <div>
	                <strong>The total amount of</strong>
	                <strong>
	                  <p class="mb-0">(including VAT)</p>
	                </strong>
	              </div>
	              <span><strong>$53.98</strong></span>
	            </li>
	          </ul>

	          <button type="button" class="btn btn-primary btn-block">go to checkout</button>

	        </div>
	      </div>
	      <!-- Card -->

	      <!-- Card -->
	      <div class="mb-3">
	        <div class="pt-4">

	          <a class="dark-grey-text d-flex justify-content-between" data-toggle="collapse" href="#collapseExample"
	            aria-expanded="false" aria-controls="collapseExample">
	            Add a discount code (optional)
	            <span><i class="fas fa-chevron-down pt-1"></i></span>
	          </a>

	          <div class="collapse" id="collapseExample">
	            <div class="mt-3">
	              <div class="md-form md-outline mb-0">
	                <input type="text" id="discount-code" class="form-control font-weight-light"
	                  placeholder="Enter discount code">
	              </div>
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- Card -->

	    </div>
	    <!--Grid column-->

	  </div>
	  <!-- Grid row -->

	</section>
<!--Section: Block Content-->
	
{% endblock %}

templates/category.html.twig
{% extends "base.html.twig" %}

{% block body %}
	<div class="row mt-10 mb-10">
		{% if announcements != null %}
			<h5 class="w-100 text-center">Annonces de {{titleCat.Category.Name}}</h5>
		{% else %}
			<h5 class="w-100 text-center">{{titleCat}}</h5>
		{% endif %}
		
	</div>

	<div class="row">
		{% for announcement in announcements %}
			{% if announcement.IsActive %}

				<div class="col-lg-4 col-md-6 mb-4 ml-5">
					<div class="card h-100">
						<!--http://placehold.it/700x400-->
						<a href="#"><img class="card-img-top" src="{{ announcement.image }}" alt=""></a>
						<div class="card-body">
							<h4 class="card-title">
							  <a href="{{ path('announcement', {'id': announcement.id}) }}">{{announcement.Title}}</a>
							</h4>
							<h5>{{announcement.Price}}€</h5>
							<p class="card-text">{{announcement.Description|length > 200 ? announcement.Description|slice(0, 200) ~ '...' : announcement.Description}}</p>
						</div>
						<div class="card-footer">
							<small class="text-muted"></small>
						</div>
					</div>
				</div>

			{% endif %}
		{% endfor %}
	</div>

{% endblock %}

templates/contact.html.twig
{% extends "base.html.twig" %}

{% block body %}

<div class="container">
<!--Section: Contact v.2-->
    <section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold my-4">Contactez nous !</h2>
    <!--Section description-->
    <!--<p class="w-responsive mx-auto mb-5">Si vous avez des questions n'hésitez pas à nous contacter</p>-->

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control" required="required">
                            <label for="name" class="">Votre Nom</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control" required="required">
                            <label for="email" class="">Votre Email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" required="required" name="subject" class="form-control">
                            <label for="subject" class="">Objet du mail</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" required="required" id="message" name="message" rows="10" class="form-control md-textarea"></textarea>
                            <label for="message">Votre Message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary" onclick="sendMailClick()">Envoyer</a>
            </div>
            <div class="status mt-5">
               <div id="alert-mail" style="visibility: hidden;" class="alert alert-success" role="alert">
                    Votre Email a été envoyé !
                </div>
            </div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <!--<ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>San Francisco, CA 94126, USA</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+ 01 234 567 89</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>contact@mdbootstrap.com</p>
                </li>
            </ul>-->
        </div>
        <!--Grid column-->

    </div>
    </section>
<!--Section: Contact v.2-->

</div>

{% block javascripts %} 
    <script type="text/javascript" src="/vendstonproduit/src/js/ajaxMail.js"></script>
{% endblock %}

{% endblock %}

templates/detail.html.twig
{% extends "base.html.twig" %}

{% block body %}
	<div class="w-100 mt-5">
		<a href="{{ path('category', {'id': announcement[0].Category.id}) }}" class="mt-5 ml-7">Retour Catégorie</a>
	</div>
	
	<div class="container mt-60 mb-50">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="preview col-md-6">
						
						<div class="preview-pic tab-content">
							<img class="card-img-top" src="http://placehold.it/700x400" alt="">	  
						</div>
						
						
					</div>
					<div class="details col-md-6">
						<h3 class="product-title">{{announcement[0].Title}}</h3>
						
						<p class="product-description">{{announcement[0].Description}}</p>
						<h4 class="price">Prix : <span>{{announcement[0].Price}}€</span></h4>
						<!--<p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>-->
						
						<div class="action mb-3">
							{% if app.user %}
								<a href="#"class="btn btn-success btn-block" type="button">Payer le service</a>
							{% else %}
								<div class="alert alert-danger text-center" role="alert">
  									<span>Veuillez vous connecter pour payer</span>
								</div>
							{% endif %}
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
  <div class="container">

      <div class="row">
        <div class="col-lg-3">
          <h1 class="my-4">One Minute</h1>
          <div class="list-group">
          {% for category in categories %}
              {% if category.IsActive %}
                <a href="{{ path('category', {'id': category.id}) }}" class="list-group-item">{{category.Name}}</a>
              {% endif %}
          {% endfor %}
        </div>
      </div>
    
      <div class="col-lg-9">
      	<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://localhost/vendstonproduit/templates/images/caroussel/bricolage.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://localhost/vendstonproduit/templates/images/caroussel/jardinage.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <!--http://placehold.it/900x350-->
              <img class="d-block img-fluid" src="http://localhost/vendstonproduit/templates/images/caroussel/menage.jpg" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>


      <div class="row col-lg-10 d-flex flex-row-reverse ml-2">
        {% for announcement in announcements %}
          {% if announcement.IsActive %}

            <div class="col-lg-4 col-md-6 mb-4 ml-5">
              <div class="card h-100">
                <!--http://placehold.it/700x400-->
                <a href="#"><img class="card-img-top" src="{{ announcement.image }}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="{{ path('announcement', {'id': announcement.id}) }}">{{announcement.Title}}</a>
                  </h4>
                  <h5>{{announcement.Price}}€</h5>
                  <p class="card-text">{{announcement.Description|length > 200 ? announcement.Description|slice(0, 200) ~ '...' : announcement.Description}}</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"></small>
                </div>
              </div>
            </div>

          {% endif %}
        {% endfor %}
      </div>

  </div>
{% endblock %}

templates/tax.html.twig
{% extends "base.html.twig" %}

{% block body %}
	
	<div class="container">
		<div class="embed-responsive embed-responsive-16by9">
			<embed class="embed-responsive-item" src="/vendstonproduit/src/Files/fiscal.pdf"></embed>
		</div>
	</div>

{% endblock %}